### ISSUE TITLE
Extra tab dossiers

### ISSUE THREAD

**Issue by claeyswo** [OnroerendErfgoed/zoneerder#11]
Naast de bestaande tab erfgoedobjecten zou er een extra tab dossiers moeten bijkomen.
Deze moet in de geozoekdiensten zoeken naar dossiers.
Extra filtering in deze tab is nodig, 1 dropdown filter om te filteren op dossiertype en 1 drpdown filter die een lijst toont van de geselecteerde objecten, indien van toepassing, en toelaat hierop te filteren.

**Comment by claeyswo** [comment]
Een beetje meer uitleg over de filtering.

Elk dossier heeft in principe steeds de attributen erfgoedobjecten en dossiers. Zie ook https://github.com/OnroerendErfgoed/dossierdata/issues/19.

Filtering op dossiertype is eenvoudigweg een call naar de geozoekdiensten.
Filtering op object moet dan een call doen naar de zoek api van dossiers (https://github.com/OnroerendErfgoed/dossierdata/issues/20) met als parameter de object uri's. Dit geeft dan een lijst terug van dossiers gelinkt aan die objecten. Client side moet deze lijst dan gecombineerd worden met de resultaten van de geozoekdiensten, i.e. enkel dossiers die op beide lijsten aanwezig zijn moeten nog getoond worden.

**Comment by claeyswo** [comment]
Dit is ook nodig voor het proces zoneren, op te nemen in de volgende sprint.

**Comment by claeyswo** [comment]
@TOM-VC voor het design

**Comment by claeyswo** [comment]
![1](https://cloud.githubusercontent.com/assets/1850704/8590532/c71ff72a-2621-11e5-937e-a7b9b317acf6.png)
![2](https://cloud.githubusercontent.com/assets/1850704/8590531/c71e9df8-2621-11e5-8699-1006427e43ad.png)
![3](https://cloud.githubusercontent.com/assets/1850704/8590533/c720ebbc-2621-11e5-9212-ff1e7093dc0b.png)

**Comment by claeyswo** [comment]
Lijst Item 1 moet worden Procestype. Daarnaast moet er ook nog ergens een knop komen 'Haal dossiers op' analoog aan 'Haal erfgoedobjecten op'. Knop Verfijn item 1 moet worden 'Filter op erfgoedobject'.

Procestype filtering is dus een multiselect. Filter op erfgoedobject toont dan een pop up met de geselecteerde erfgoedobjecten uit de tab erfgoedobjecten. Tot slot is er nog een knop om alle filters ongedaan te maken.

**Comment by cedrikv** [comment]
Heel de layout moet eigenlijk bij de applicatie komen die de zoneerder gebruikt. In dit geval Adviezen? De zoneerder zelf kan als tussenlaag gebruikt worden om data op te halen (zoals de erfgoedobjecten).

**Comment by claeyswo** [comment]
Proces zoneren. Ik verplaats dit ticket zodra de tickets daar aangemaakt zijn.

**Comment by cedrikv** [comment]
bump

**Comment by BartSaelen** [comment]
issues worden momenteel aangemaakt
https://github.com/OnroerendErfgoed/proces_zoneren/issues

**Comment by BartSaelen** [comment]
zie ook https://github.com/OnroerendErfgoed/projecten/blob/master/adviezen-zoneren/source/userstories.rst
