### ISSUE TITLE
Selecteer bescherming

### ISSUE THREAD

**Issue by claeyswo** [OnroerendErfgoed/zoneerder#12]
Net zoals er nu een knop is selecteer perceel moet er een knop bijkomen selecteer bescherming die de afbakening van de beschermde objecten overneemt.

**Comment by dieuska** [comment]
Mockup voor zoneerder

![zoneerder_wireframe 3](https://cloud.githubusercontent.com/assets/7127298/8059718/c8d2cab0-0ec1-11e5-9940-4a5ddf5871db.png)

**Comment by cedrikv** [comment]
Het overzichtslijstje is wel enkel mogelijk tijdens het intekenen, na opslaan is er maar 1 zone (alle info ivm bvb de onderliggende percelen wordt niet mee opgeslagen). Er blijft dus enkel een multipolygoon over. 
Bij editeren van bestaande zone is het dus niet mogelijk om een 'deelzone' te gaan flashen, deleten,...

**Comment by cedrikv** [comment]
Tussentijdse versie:
![zoneerder](https://cloud.githubusercontent.com/assets/1849458/8499201/2fe28ca0-2190-11e5-8919-0983db53ed6a.png)

Hier al opmerkingen over?

**Comment by BartSaelen** [comment]
ziet er al veel beter uit dan de huidige versie

**Comment by dieuska** [comment]
ziet er goed uit!

enkele opmerkingen:
*Typo in Zone: polyogoon
* Bij toevoegen WKT:  Als ze de string erin hebben geplakt, is er dan een button die deze polygoon effectief aan de Zone-lijst toevoegt? 
-(Mss ervoor een PLUS- icoon voor WKT zetten, waarop geduwd kan worden om de WKT-string effectief aan de lijst toe te voegen? Of is de tekst 'WKT' momenteel clickable voor de toevoeging effectief uit te voeren?

**Comment by koenedaele** [comment]
Ik mis nog ergens een ninja. Of een dinosaurus. Of een ninja op een dinosaurus.

**Comment by cedrikv** [comment]
Zoiets?

![ninjadino](https://cloud.githubusercontent.com/assets/1849458/8500109/725e236a-2199-11e5-943c-9c27f9fb8f5f.png)

**Comment by cedrikv** [comment]
of is de boog er wa over?

**Comment by cedrikv** [comment]
@Karel: WKT voor het inputveld is inderdaad de knop die je zoekt, maar dan nog ongestijld.

**Comment by koenedaele** [comment]
Vervang de boog door shuriken en 't is perfect!

**Comment by cedrikv** [comment]
Ik ben niet helemaal zeker welke logica er nog achter de 'bewaar' en annuleren' knoppen moet zitten, als je ervan uit gaat dat de zoneerder in een andere app ingebed wordt:
-In principe wordt een zone bewaard op het niveau van de app, bvb adviezen. de zone extra moeten bewaren kan verwarrend zijn. hetzelfde voor annuleren.
-bij annuleren is er nog een extra use case dat je je huidige teken of selecteer actie wilt apart annuleren, zonder al je vorige edits teniet te doen

**Comment by dieuska** [comment]
Bewaren en annuleren zijn idd verwarrende namen indien dit ingebed zit in de app waar je de effectieve 'save' uitvoert.

Toch lijkt mij mss handig om hier 2 buttons te hebben (met een betere naam):
*button 1: Ik wil het zoneren afsluiten en ben akkoord met mijn zonering. 
*button 2: ik wil het zoneren afsluiten en ge moogt al mijn acties op de zoneringspagina negeren

Wat zou een betere benaming zijn? 
button 1: OK
button 2: Annuleer/Negeer/Sluit af

Ofwel houden we het simpel en voorzien we enkel één button om het zoneringsvenster af te sluiten 
(en indien gewenst zetten we ergens anders op de pagina een 'reset' button om naar de oorspronkelijke zonering te gaan...)

**Comment by cedrikv** [comment]
Ik vrees voor verwarring bij de gebruikers. In de andere tabs van de beheer interfaces (relaties, bestanden,..) moet er niet apart op 'ok' geklikt worden. Je hebt de algemene 'opslaan' en 'annuleren', die dan voor alle tabs gelden. 
Wat gebeurt er bvb als iemand niet klikt op button 1? gaan al zijn bewerkingen verloren als het beheersplan opgeslagen wordt?

Je kan het zoneren ook niet 'afsluiten', zolang het beheersplan in de editeer mode zit zit zal dit ook zo zijn voor de zoneerder.

Een aparte annuleer knop kan nog nuttig zijn, maar in de andere tabs is dit ook niet. Dankzij het extra grid met alle zones kan je ook gewoon zelf je aanpassingen terug verwijderen.

**Comment by claeyswo** [comment]
+1 om die knoppen gewoon te verwijderen

**Comment by dieuska** [comment]
idd hoe minder knoppen hoe beter, dus als alle cases zijn opgevangen voor de gebruiker door de algemene knoppen van de applicatie, des te beter.

(een herstel/reset-knop is mss een nice to have, maar lijkt me enkel nuttig indien dit op vraag van de gebruikers komt en ze dit dus effectief nodig hebben)

**Comment by claeyswo** [comment]
De verschillende lagen voor de beschermingen:

```
vioe_geoportaal:beschermde_landschappen
vioe_geoportaal:beschermde_dorps_en_stadsgezichten
vioe_geoportaal:beschermde_archeologische_zones
vioe_geoportaal:beschermde_monumenten
```

Ik denk niet dat het hier nodig is om geïnventariseerd erfgoed te kunnen selecteren. Enkel de koppeling moet kunnen gelegd worden.

@koenedaele De vraag van @cedrikv was of het niet mogelijk is de 4 bovenstaande lagen te bevragen met 1 call?

**Comment by vanbosa** [comment]
vioe:beschermde_landschappen
vioe:beschermde_archeologische_sites
vioe:beschermde_monumenten
vioe:beschermde_dorps_en_stadsgezichten

geoportaal lagen geven geen data weer.

Volgende week is zien als dev geo geoserver actief is
dev-geo geoserver opzetten: ogc script, vervangen door tomcat instellingen/settings
beschermingen rechtstreeks doen ipv porxy script.

wfs bevragen en werken met views. 
outputFormat json ipv van default xml.

**Comment by cedrikv** [comment]
Note van Koen: check code in geoportaal voro wfs calls (ivm lagen combineren & stijl)
