### ISSUE TITLE
Mogelijkheid voorzien om niscodes van administratieve grenzen op te halen

### ISSUE THREAD

**Issue by claeyswo** [OnroerendErfgoed/zoneerder#13]

**Comment by claeyswo** [comment]
Nog verder uit te schrijven.

**Comment by claeyswo** [comment]
Use case is bij de toelatingen te kunnen kijken voor een bepaalde afbakening welke de niscodes zijn en deze dan bij te houden in een extra veld in de authentieke bron adviezen.

**Comment by cahytinne** [comment]
![plantuml-2ad2f258db9026cb4d294c2ba36423c66c6bf003](https://cloud.githubusercontent.com/assets/7933103/7511210/7fc131aa-f4a3-11e4-86f9-c91de4f67df5.png)

**Comment by claeyswo** [comment]
Achteraf moeten die resultaten voor niscode dan server side, voor adviezen, sowieso nog worden overschreven ook door een call naar de geozoekdiensten/administratievegrenzen

**Comment by koenedaele** [comment]
@claeyswo Heb je het nu over validatie van de doorgestuurde data of iets helemaal anders?

**Comment by claeyswo** [comment]
Dat is moeilijk nog validatie te noemen, hetgeen wordt doorgestuurd moet gewoon worden weggesmeten en overschreven, maar dat is eigenlijk iets voor adviezen zelf: https://github.com/OnroerendErfgoed/adviezen/issues/21

**Comment by koenedaele** [comment]
Klopt. Moet de zoneerder dan überhaupt nog een call naar de administratievegrenzen doen? Kan dat niet gewoon overgelaten worden aan de adviezen server side?

**Comment by claeyswo** [comment]
Ik dacht dat het nog een leuke feature was om aan de eindgebruiker de resultaten al te laten zien, het kan bovendien later nog van pas komen voor andere projecten, maar voor de adviezen is het geen noodzaak om van start te gaan.

**Comment by koenedaele** [comment]
Ok. Eerst en vooral die service op poten krijgen dus.
