### ISSUE TITLE
zoneMap.setZone verwijdert de reeds getekende zones niet?

### ISSUE THREAD

**Issue by taeymma** [OnroerendErfgoed/zoneerder#18]
Als ik bij adviezen op de zoneerder een zone teken, op bewaren klik en dan 'reset' (zoneMap.setZone met orginele zone) dan wordt de getekende zone niet verwijderd.

**Comment by cahytinne** [comment]
https://github.com/OnroerendErfgoed/zoneerder/commit/9b63e75010c968cdfbc086d6cfb6741056e7327d
