### ISSUE TITLE
Laag van inventarisobjecten toevoegen

### ISSUE THREAD

**Issue by claeyswo** [OnroerendErfgoed/zoneerder#20]
Op dit moment kan ik enkel beschermd erfgoed aanvinken.

**Comment by cedrikv** [comment]
waar zit die laag juist? wms/laagnaam

**Comment by claeyswo** [comment]
wms idem aan die van beschermingen, vioe:dibe_geheel en vioe:dibe_relict als lagen denk ik.

@koenedaele Klopt dit?

**Comment by koenedaele** [comment]
Klopt. Die twee vormen bouwkundig erfgoed.

Daarnaast zijn er ook nog twee landschapslagen die momenteel nuttig zijn:
* ile_park (tuinen en parken)
* ile_boom (houtig erfgoed)

**Comment by cedrikv** [comment]
Lagen zijn toegevoegd, momenteel zijn dit dus:
                        'LAYERS': 'vioe_geoportaal:beschermde_landschappen,' +
                                  'vioe_geoportaal:beschermde_dorps_en_stadsgezichten,' +
                                  'vioe_geoportaal:beschermde_archeologische_zones,' +
                                  'vioe_geoportaal:beschermde_monumenten,' +
                                  'vioe_geoportaal:dibe_geheel,' +
                                  'vioe_geoportaal:dibe_relict,' +
                                  'vioe_geoportaal:ile_park,' +
                                  'vioe_geoportaal:ile_boom',
