### ISSUE TITLE
Mogelijkheid voorzien om opgehaald erfgoed op de kaart aan te klikken

### ISSUE THREAD

**Issue by claeyswo** [OnroerendErfgoed/zoneerder#21]
Bedoeling is dan een soort rapportje te tonen met de naam en nummer van het object, nu is dit niet duidelijk.

**Comment by cedrikv** [comment]
@claeyswo : Is dit wat je in gedachten had?
![popup](https://cloud.githubusercontent.com/assets/1849458/7956074/cb6cdeac-09dd-11e5-9db5-065d795fae10.png)

**Comment by claeyswo** [comment]
Perfect, misschien gewoon nog is kijken om het iets leesbaarder te maken. Achtergrond niet doorzichtig maken?

**Comment by cedrikv** [comment]
Transparency wat lager gezet en nog wat styling toegevoegd:
![popup2](https://cloud.githubusercontent.com/assets/1849458/7960136/6b340f30-09fe-11e5-93ce-f6c7a437aca8.png)
