### ISSUE TITLE
Beschermd erfgoed wordt niet correct opgehaald

### ISSUE THREAD

**Issue by claeyswo** [OnroerendErfgoed/zoneerder#22]
Zie screenshot, nummer zou 4.01... moeten zijn en omschrijving klopt ook niet volledig:

Van xxx.yyy/yyy/yyy.zzz maakt hij yyy/yyy/yyy, alles voor en na de punten wordt verwijderd.

![image](https://cloud.githubusercontent.com/assets/1850704/7703736/401131c2-fe3a-11e4-9801-8b47fabd8879.png)

**Comment by claeyswo** [comment]
Omschrijving is wel correct maar Type veld zou iets breder mogen zijn.
Misschien dat we daar ook beter werken met een soort vertaallijst, die namen nu zijn niet echt duidelijk voor externen.

@koenedaele Wat denk jij?

**Comment by cahytinne** [comment]
Dit is geen probleem van de zoneerder

Het visserhuis Tulpenlaan uit zoneerder:
```json
{
"categorie": "objecten",
"geometrie": {"crs": {"type": "name", "properties": {"name": "EPSG:31370"}}, "type": "MultiPolygon",…},
"id": "OW001461",
"naam": "vissershuisje (tulpenlaan)",
"type": "erfgoedobjecten",
"uri": "https://id.erfgoed.net/beschermingen/OW001461"
}
```

Het visserhuis Tulpenlaan uit uri:
```json
{
"description": null,
"id": "4.01/38014/317.1",
"locatie": {"geometry": {"type": "MultiPolygon",…}},
"naam": "Tulpenlaan 46 : vissershuisje",
"type": "bes_bescherming_monument",
"uri": "https://id.erfgoed.net/beschermingen/4.01/38014/317.1"
}
```

Het probleem gebeurt bij het parsen van het beschermingsobject verkregen van de uri in de Adviezen applicatie.

**Comment by cahytinne** [comment]
Is het normaal dat een bescherming 2 verschillende id's heeft? OW001461 en 4.01/38014/317.1?

**Comment by koenedaele** [comment]
Da's een lang verhaal.

OW001461 is het nummer uit het oude Melanie systeem. 4.01/38014/317.1 is het nummer in Bredero, dat de opvolger is van Melanie.

Op dit moment gaan beide URI's op hetzelfde object uitkomen, maar  het is inderdaad verwarrend.
