### ISSUE TITLE
Objecten verwijderen werkt niet goed

### ISSUE THREAD

**Issue by claeyswo** [OnroerendErfgoed/zoneerder#23]
- Baken een zone af met meerdere erfgoedobjecten
- Bewaar zone
- Haal erfgoedobjecten op
- Selecteer ze nu allemaal en verwijder
- Een deel blijft gewoon staan, er zijn meerdere verwijder operaties nodig om alles weg te krijgen

**Comment by cedrikv** [comment]
hier hebben we al naar gekeken, issue komt omdat grid aan lazy loading doet, en 'select all' enkel werkt op de huidige zichtbare records. We zulle workaround zoeken.

**Comment by cahytinne** [comment]
Dit is een issue dat bij adviezen hoort.
