### ISSUE TITLE
Milestones en releases eens bekijken

### ISSUE THREAD

**Issue by claeyswo** [OnroerendErfgoed/zoneerder#24]
Eens kijken om een release aan te maken en milestones te definieren, geen idee hoe we dit bij js componenten opvangen. Of is dit gewoon gelijk aan python projecten?

@koenedaele @kmillet

**Comment by cedrikv** [comment]
idem voor actor widget en crabpy_dojo widget

**Comment by koenedaele** [comment]
Ook hier volgen we dezelfde regels als bij python projeten. Semantic versioning; http://semver.org/.

Bij elke release een tag aanmaken. Misschien de versie die meegaat met de eerste produktie app gelijkstellen met 0.1.0 of 1.0.0? Hangt er van af hoe stabiel de API ondertussen is. Ik zou uitgaan van 0.1.0 en van daar af verder gaan. Als we na een tijdje merken dat het goed zit kunnen we naar 1.0.0 springen.

Momenteel verwijzen we in de bower.json files altijd naar de master op github. We zouden ofwel releases op bower moeten doen. Dan kunnen we "zoneerder": "0.1.0" gebruiken. Ofwel rechtstreeks naar github blijven gaan, maar dan ook wel met een tag (geen idee hoe die syntax er juist uitziet).
