### ISSUE TITLE
Add 'zoom to objecten' control to the map

### ISSUE THREAD

**Issue by cedrikv** [OnroerendErfgoed/zoneerder#34]
Like in public frontend map

**Comment by dieuska** [comment]
Deze functionaliteit wordt meegepakt samen met refactoring van frontend zoneerder ikv nieuwe selectiemogelijkhed ('Selecteer bescherming')

zie mockup: https://github.com/OnroerendErfgoed/zoneerder/issues/12

**Comment by cedrikv** [comment]
Dingen om mee rekening te houden
-de nieuwe selectiemogelijkheid zit in de sidebar van de zoneerder, deze is enkel beschikbaar in de edit view. 
-het is ook niet mogelijk om naar de erfgoedobjecten te zoomen, enkel naar de zone.
