### ISSUE TITLE
Geometrie van geselecteerde bescherming is niet gelijk aan origineel

### ISSUE THREAD

**Issue by cedrikv** [OnroerendErfgoed/zoneerder#37]
Als er een bescherming geselecteerd wordt, komt de geometrie niet 100% overeen met de bron data:
![zoneerder](https://cloud.githubusercontent.com/assets/1849458/9219764/699fde86-40dd-11e5-8e6d-9711cf140fd3.png)

De getekende polygoon krijgt zijn coördinaten via een getfeatureinfo op https://dev-geo.onroerenderfgoed.be/mapproxy/service, de onderliggende tiles komen van https://dev-geo.onroerenderfgoed.be/geoserver/wms

**Comment by cedrikv** [comment]
Wordt deze geometrie op de geoserver gegeneraliseerd? Of misschien op openlayers niveau? Uit te zoeken..
Kan de impact niet inschatten, heb deze dus nog niet in een milestone gestoken. Feel free om er een bug label aan te hangen en in milestone te steken.

**Comment by claeyswo** [comment]
@maarten-vermeyen @koenedaele 

Ken hier te weinig van om een zinnig antwoord te geven.

**Comment by BartSaelen** [comment]
is er een mogelijke relatie met dit probleem waar we ook afrondingsverschillen hebben?
https://github.com/OnroerendErfgoed/adviezen/issues/211

**Comment by cedrikv** [comment]
Ik vermoed van niet, daar zit de geozoekdienst er voor iets tussen denk ik. Maar moet zeker eens afgecheckt worden.

**Comment by maarten-vermeyen** [comment]
Het probleem van adviezen zal zich ook hier stellen, maar hier lijkt echt een simplify te zijn gebeurd.

**Comment by koenedaele** [comment]
De mapproxy service proxiet de geoserver. Op zich komen zowel de GetFeatureInfo als de WMS uit dezelfde data. Ik heb even naar de proxy config gekeken en daar staat niet in dat deze het resultaat moet simplifyen. Er wordt naar de geoserver wel een buffer:10 meegestuurd, maar volgens mij heeft dat mogelijk een impact op welke features worden teruggegeven, maar niet op de eigenlijke waarde van die features.

Nu, we hebben al gesproken over het aanbieden van geoserver met CORS headers zodat we de GetFeatureInfo Requests niet meer moeten proxien. Heeft er al een iemand beide requests rechtstreeks naar https://geo.onroerenderfgoed.be/geoserver gestuurd om te vergelijken?Alhoewel het moeilijk is een GetFeatureInfo te vergelijken met een WMS. Misschien de GetFeatureInfo vergelijken met een WFS request?

**Comment by cedrikv** [comment]
Ik zal ook eens in QGIS testen, om ol te kunnen uitsluiten

**Comment by cedrikv** [comment]
ter info, voorbeeld request:
https://dev-geo.onroerenderfgoed.be/mapproxy/service?SERVICE=WMS&VERSION=1.3.0&REQUEST=GetFeatureInfo&FORMAT=image%2Fpng&TRANSPARENT=true&QUERY_LAYERS=vioe_geoportaal%3Abeschermde_landschappen%2Cvioe_geoportaal%3Abeschermde_dorps_en_stadsgezichten%2Cvioe_geoportaal%3Abeschermde_archeologische_zones%2Cvioe_geoportaal%3Abeschermde_monumenten&LAYERS=vioe_geoportaal%3Abeschermde_landschappen%2Cvioe_geoportaal%3Abeschermde_dorps_en_stadsgezichten%2Cvioe_geoportaal%3Abeschermde_archeologische_zones%2Cvioe_geoportaal%3Abeschermde_monumenten&TILED=true&info_format=application%2Fvnd.ogc.gml&feature_count=10&I=14&J=158&WIDTH=256&HEIGHT=256&CRS=EPSG%3A3857&STYLES=&BBOX=468253.23527498916%2C6617917.908930559%2C468406.1093315595%2C6618070.782987129

**Comment by cedrikv** [comment]
Soooo, is er ondertussen iets gebeurd op serverniveau? Probleem is 'verdwenen':
![zoneerder2](https://cloud.githubusercontent.com/assets/1849458/9221871/c2f09f9c-40ed-11e5-829b-e4408d3dc34d.png)

**Comment by claeyswo** [comment]
Niet dat ik weet, vanmorgen geozoekdiensten op dev gedeployed maar dat was rond 10u.

**Comment by cedrikv** [comment]
Ok, ik heb het eindelijk door: als de selectie gebeurt wanneer je sterk uitgezoomd bent, wordt er een simplify op de polygoon uitgevoerd. De simplify zit al in de response van geoserver (getest via QGIS), en gebeurt dus aan serverzijde. Geoserver houdt rekening met de huidige staat van de kaart, waardoor detail kan verloren gaan.
Uit te testen: doet dit scenario zich ook voor met een wfs call (momenteel is het een getfeatureinfo op een wms)

**Comment by cedrikv** [comment]
request omgezet naar wfs call
