### ISSUE TITLE
Gewestplan - wat tonen bij uitzoomen

### ISSUE THREAD

**Issue by cedrikv** [OnroerendErfgoed/zoneerder#66]
Het gewestplan wordt maar getoond tot een bepaald schaalniveau opgelegd door agiv, wat zouden we tonen als er te veel uitgezoomd wordt?

**Comment by cedrikv** [comment]
> Voor overlays hebben we het zo al gedaan dat ze pas vanaf een bepaald schaalniveau zichtbaar zijn, maar voor baselayers lijkt dat me moeilijk. Kunnen we van het gewestplan een soort combilaag maken? Als deze aanstaat, tot schaalniveau X de topokaart tonen en vanaf schaalniveau X het gewestplan tonen?
Groeten,
 Koen

**Comment by koenedaele** [comment]
Zit er in OL3 iets wat zo'n combilayer makkelijk maakt? Kan me voorstellen dat er ooit nog wel iemand hetzelfde probleem heeft gehad?
Of moeten we gewoon aan het AGIV vragen om de ontbrekende zoomniveaus in te vullen met de grenzen van Vlaanderen en/of provincies en/of gemeentes.

**Comment by cedrikv** [comment]
zal eens de mogelijkheden checken

**Comment by cedrikv** [comment]
Ik kan er een group layer van maken, en dan met de minextent/maxextent wisselen tussen 2 lagen.
Via de grb wms service kan ik bvb de basis vlaanderen contour nemen (op gemeentegrenzen zit ook een max extent):
![image](https://cloud.githubusercontent.com/assets/1849458/11688636/17c5fb72-9e8e-11e5-9dc2-f5d9a59ade17.png)

**Comment by cedrikv** [comment]
Correctie: gemeentegrenzen kan wel, had foute id gebruit. eventueel aangevuld met toponiemen en/of de achtergrond van hierboven (maar dan lijkt het sterk op grb):
![image](https://cloud.githubusercontent.com/assets/1849458/11688823/19662942-9e8f-11e5-923a-38bbf1633c6c.png)

**Comment by koenedaele** [comment]
Ik zou schakelen tussen gemeentegrenzen en gewestplan. Lijkt dan inderdaad fel op GRB voor die eerste niveaus, maar dat is denk ik niet zo erg.

**Comment by cedrikv** [comment]
ok. De labels en/of gelige vlaanderen achtergrond er ook op zetten?

**Comment by koenedaele** [comment]
Als je die gelige achtergrond onder de grenzen legt, moet je dan 2 tegels binnenhalen of is er een combitegel?

Labels zijn niet slechts, alleen vind ik de labels in het voorbeeld vreemd. Who gives a fuck about Roeselare?
