### ISSUE TITLE
Update AGIV Wfs url

### ISSUE THREAD

**Issue by cedrikv** [OnroerendErfgoed/zoneerder#74]
~~https://geoservices.informatievlaanderen.be/ogc/wfs/grb~~
http://geoservices.informatievlaanderen.be/overdrachtdiensten/GRB/wfs
ipv 
https://geo.agiv.be/ogc/wfs/grb

en laagnaam van administratieve percelen is veranderd naar: GRB:ADP

**Comment by taeymma** [comment]
refs https://github.com/OnroerendErfgoed/geoportaal/issues/278

**Comment by cedrikv** [comment]
fixed in dev_0.5 (d5436e7c7890849f880b94604ab94493d74e420f)
