### ISSUE TITLE
default zoomniveau aanpassen naar Vlaanderen

### ISSUE THREAD

**Issue by jolijnleen** [OnroerendErfgoed/zoneerder#75]
Default zoomniveau van kaart bij meldingen vooronderzoek, nota's is redelijk ver uitgezoomd:

![meldingen_vooronderzoek_locatie](https://cloud.githubusercontent.com/assets/12525411/14011721/21003e08-f1a1-11e5-8d4d-227644323462.PNG)

Kan dit aangepast worden naar bv: (zoomextent Vlaanderen)
![locatie_zoomniveau](https://cloud.githubusercontent.com/assets/12525411/14011724/2328167e-f1a1-11e5-92fa-f7719eae75d7.PNG)

**Comment by cedrikv** [comment]
fixed in https://github.com/OnroerendErfgoed/zoneerder/commit/fb1fb3a404acc0c14b5e2e6d93f72df5bb737731

**Comment by jolijnleen** [comment]
Default zoomniveau is aangepast, maar bij meldingen vooronderzoek is het 1 keer meer ingezoomd dan bij nota's/archeologienota's. Enig idee waarom dit verschilt? @taeymma @cedrikv 

![default_zoomniveau_mv](https://cloud.githubusercontent.com/assets/12525411/14385130/1b412b76-fd9f-11e5-83a4-4adb7d39ae28.PNG)
![default_zoomniveau_nota s](https://cloud.githubusercontent.com/assets/12525411/14385132/1e4a7b1a-fd9f-11e5-900f-e03bdff65e29.PNG)

**Comment by cedrikv** [comment]
:grimacing:
