### ISSUE TITLE
Maak het mogelijk om shape- of wkt-file te uploaden in de zoneercomponent.

### ISSUE THREAD

**Issue by cedrikv** [OnroerendErfgoed/zoneerder#8]
ref https://github.com/OnroerendErfgoed/beheersplannen/issues/137

**Comment by dieuska** [comment]
(Besproken op sprintmeeting 3 (17/3/2015)): Mogelijkheid om geselecteerde feature te kopieren vanuit QGIS (WKT +attributen) en deze WKT in de zoneercomponent te gebruiken.

**Comment by cedrikv** [comment]
Niet beschikbaar in openlayers zelf, maar er bestaan wel javascript libraries voor:
https://github.com/tlahoda/shapefile
https://github.com/RandomEtc/shapefile-js
https://github.com/wavded/js-shapefile-to-geojson

**Comment by koenedaele** [comment]
Even vlug gekeken. De meeste van die projecten lijken aan te geven dat ze niet produktieklaar zijn. Op dit moment lijkt de WKT oplossing me veruit de best haalbare en mature.

**Comment by cahytinne** [comment]
Eerste versie:
- input veld waar wkt ingevoerd kan worden in Lambert 72
- wanneer er geen geldige wkt ingevoerd wordt, verschijnt er een melding
- na invoer, zoomen naar polygoon die toegevoegd is aan de zone

**Comment by dieuska** [comment]
Uitbreiding (op vraag van Maarten):
Hierbij gaan we toch moeten mogelijk maken dat ook de volledig gekopieerde inhoud (=wkt +attributen) zoals gekopieerd uit QGIS in het veld wordt geplakt.
Er wordt dus in de volledig textuele inhoud gekeken of er een WKT in zit en die wordt dan gebruikt.

nota:Enkel het invoeren van de WKT blijft dus ook geldig als aan bovenstaande uitbreding voldaan is!

**Comment by cedrikv** [comment]
Voorbeeld input:
wkt_geom	id	onderwerp	datum_goedkeuring	startdatum	einddatum	beheerscommissie	created_at	created_by	updated_at	updated_by
MULTIPOLYGON(((103827.44294596120016649 192484.51032156220753677,103826.65594634690205567 192565.57053245700080879,103839.19982519210316241 192622.49615116600762121,103877.27230024100572336 192673.19146609399467707,103981.90780607200576924 192592.71611812341143377,104050.62808197719277814 192535.07291979811270721,104119.78579141720547341 192526.95887319461326115,104157.55264062809874304 192543.13741146030952223,104163.3345441722049145 192516.06887603359064087,104043.86767558539577294 192451.0768509590998292,103839.39204890849941876 192304.2816991257132031,103825.49935774100595154 192434.99438346829265356,103827.44294596120016649 192484.51032156220753677)))	5	Mijn plan				f	2015-04-21 13:38:32.507849	nepgebruiker	2015-04-22 08:05:46.693488	nepgebruiker

**Comment by cedrikv** [comment]
@koenedaele Had jij dan al code om zulke strings te parsen?

**Comment by koenedaele** [comment]
Zie naar https://github.com/OnroerendErfgoed/kvd/blob/master/classes/gis/geometry/KVDgis_GeomGeometry.class.php
