### ISSUE TITLE
Multipolygonen ondersteunen bij WKT input

### ISSUE THREAD

**Issue by cedrikv** [OnroerendErfgoed/zoneerder#90]

**Comment by cedrikv** [comment]
Ok, heb multipolygoon wkt om te testen:
```
MULTIPOLYGON(((114923.3125 184758.375,114916.375 184747.8125,114927.1875 184753.875,114923.3125 184758.375)),((114912.21875 184752.21875,114914.46875 184744.78125,114909.34375 184749.4375,114912.21875 184752.21875)),((114923.25 184748.1875,114919.21875 184746.28125,114924.6875 184745.3125,114923.25 184748.1875)))
```

**Comment by cedrikv** [comment]
Met deze wkt lukt het:
![image](https://cloud.githubusercontent.com/assets/1849458/16334279/35d87f5a-3a00-11e6-9e72-e08a300f1fde.png)

Deze wkt heb ik uit postgis gehaald via een ST_AsText(contour) op de notas tabel.

**Comment by cedrikv** [comment]
@maarten-vermeyen Is er een bepaalde wkt waar het niet mee lukt

**Comment by maarten-vermeyen** [comment]
https://gist.github.com/maarten-vermeyen/8e0a1f279c0d7f503d813ac78e7a468f

**Comment by cedrikv** [comment]
Ook geen probleem mee:
![image](https://cloud.githubusercontent.com/assets/1849458/16337026/992ba1ba-3a12-11e6-9084-2c543d186630.png)

Tina Turner:
>Solid as a rock

**Comment by claeyswo** [comment]
@maarten-vermeyen Klopt bovenstaande? Kan jij dat dan toevoegen op productie? Ik heb ondertussen de bijlage gekoppeld.

**Comment by cedrikv** [comment]
Aha, ik krijg wel een error als ik die ingeef bij nota's. Er loopt iets fout bij de call naar https://dev-loket.onroerenderfgoed.be/archeologie/notas/check_within_flanders
{"message": "De geojson geometrie is niet geldig.", "errors": ["geometrie is geen geldig GeoJson"]}

**Comment by cedrikv** [comment]
Ook bewaren lukt niet:
{"message": "De nota kon niet worden bewaard.", "errors": ["Contour: geometrie is geen geldig GeoJson"
]}

**Comment by cedrikv** [comment]
@cahytinne Er gaat iets fout bij de validatie:
TopologyException: Input geom 0 is invalid: Self-intersection at or near point 116953.02619780632 203168.28159872012 at 116953.02619780632 203168.28159872012

De payload die naar check_within_flanders gestuurd wordt:
https://gist.github.com/cedrikv/8d74cdf4494c125b4ca2811e30387497

**Comment by cahytinne** [comment]
https://gist.github.com/cahytinne/0fea762e11622ab490b31651150a6834

**Comment by cedrikv** [comment]
Zit de fout dan in de originele wkt, of in de payload die vanuit de zoneerder gestuurd wordt?

**Comment by cahytinne** [comment]
De geometrie was inderdaad niet geldig. Er was één self-intersecting multipolygoon.

In de backend code wordt dit gedeeltelijk opgevangen door een union uit te voeren bij een self-intersecting multipolygoon. Dit faalde, waarschijnlijk omdat de multipolygoon niet in afzonderlijke polygonen meer op te delen was. 

Het er manueel een buffer van 0 meter op toegepast. Nu is het wel een geldige multipolygoon. Heb het gecheckt met 'validate geometry'. Deze heb ik hierboven toegevoegd.

**Comment by cahytinne** [comment]
Fout in originele geometrie. Misschien toch nog eens nadenken om die buffer methode in backend validatie toe te voegen.

**Comment by cedrikv** [comment]
@maarten-vermeyen moeten wij de foute wkt zelf gaan corrigeren, of gaan we ervan uit dat de gebruikers correcte date moeten ingeven?

**Comment by claeyswo** [comment]
> Misschien toch nog eens nadenken om die buffer methode in backend validatie toe te voegen.

@maarten-vermeyen Ken te weinig van gans het GIS gebeuren om hierop te antwoorden. Doen of niet?

**Comment by cedrikv** [comment]
Wa ne zotte geometrie is da eigenlijk? Dit is niet wat we in gedachten hadden bij het behandelen van contouren. de call naar AGIV voor de percelen op te halen bvb is super zwaar. Hij is er hierjuist wel doorgekomen, maar ik kan mij voorstellen dat daar al eens een time-out zal optreden..

**Comment by koenedaele** [comment]
Mijn ervaring met ons beleidsveld is dat je het zo zot niet kunt bedenken of het is wel ergens een mogelijke invoer. Heb er mee leren leven...

Op zich ben ik van mening dat we niet kunnen blijven truckjes toepassen om ongeldige data toe te passen. Natuurlijk is het bij zo'n giga-polygoon veel moeilijker om de fout te vinden voor een onwetende eindgebruiker.

**Comment by maarten-vermeyen** [comment]
Nee, geen aanpassingen nodig dan. Het is niet zoveel werk om hier een geldige polygoon van te maken in QGIS, en dat zullen de archeologen dan maar moeten doen.

De polygoon zijn eigenlijk gebufferde punten van hoogspanningsmasten en gebufferde lijnen voor aan te leggen werfwegen, Aangezien dit één bouwaanvraag is, is het ook één archeologienota...

Ik sluit hierbij het ticket af, en concludeer dat het systeem functioneerde zoals voorzien. ;-)
